#!/bin/sh

DOTFILES="~${PWD#$HOME}"

case "$1" in
	git )
		git config --global include.path "$DOTFILES/git/.gitconfig"
		;;
	hammerspoon )
		mkdir -p $HOME/.hammerspoon/
		echo "dofile('..${PWD#$HOME}/hammerspoon/init.lua')" >> $HOME/.hammerspoon/init.lua
		;;
	tmux )
		echo "source-file $DOTFILES/tmux/.tmux.conf" >> $HOME/.tmux.conf
		;;
	vim )
		echo "source $DOTFILES/vim/.vimrc" >> $HOME/.vimrc
		;;
	zsh )
		echo "source $DOTFILES/zsh/.zshrc" >> $HOME/.zshrc
		;;
	* )
		echo 'Usage: init [git|hammerspoon|tmux|vim|zsh]'
		;;
esac
